### ISSUE TITLE
AutoregistrarSettingsRepository

### ISSUE THREAD

**Issue by vial0ft** [eveloth/ev-autoreg#10]
https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Data/Repository/AutoregistrarSettingsRepository.cs#L19

https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Data/Repository/AutoregistrarSettingsRepository.cs#L59

id всегда 1 ?

**Comment by eveloth** [comment]
Да, Id всегда 1 :) 

Переработал таблицу `autoregistrar_settings`, чтобы была возможность в принципе убрать Id за ненадобностью.
