### ISSUE TITLE
Include deleted 

### ISSUE THREAD

**Issue by vial0ft** [eveloth/ev-autoreg#11]
https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Data/Repository/UserRepository.cs#L56-L60

кажется это можно вынести в отдельную функцию и сделать однообразным с этим

https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Data/Repository/UserRepository.cs#L80-L84

**Comment by eveloth** [comment]
Создал `FilerQueryBuilder`, который генерирует SQL согласно переданным ему фильтрам, для #12 аналогично.
