### ISSUE TITLE
Offset Limit

### ISSUE THREAD

**Issue by vial0ft** [eveloth/ev-autoreg#12]
https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Data/Repository/QueryParametersRepository.cs#L26-L32

вот эта часть повторяется во многих местах. Почему бы не вынести её в какие нибудь утилиты и переиспользовать?

**Comment by eveloth** [comment]
Создал `FilterQueryBuilder`, который генерирует SQL согласно переданным ему фильтрам по аналогии с  #11.
