### ISSUE TITLE
PaginationQuery

### ISSUE THREAD

**Issue by vial0ft** [eveloth/ev-autoreg#9]
Не нашёл в коде валидацию [PaginationQuery](https://github.com/eveloth/ev-autoreg/blob/2607f089032f9465c739f6a406e86a8c959b8b4c/src/EvAutoreg.Api/Contracts/Queries/PaginationQuery.cs) на пограничные значения (кроме как если PageSize > 100).

Плюс: 
Такое ошушение, что `PaginationQuery` не совсем корректно работает потыкал в свагере  `/api/access-control/roles`  кажется что независимо от параметров возвращается один и тот же результат:

выставил:
PageNumber = 1
PageSize = 1

вернулся список из 2 значений

**Comment by eveloth** [comment]
Добавил проверки на пограничные значения. Логика `PaginationQuery` отрабатывается корректно, по итогам обсуждения выяснили, что Swagger просто отобразил пример стандартного успешного ответа.
